dataloader:
  batch_size: 64
dataset:
  base_path: Images
  class: leather
  img_size: 256
  name: MVTecAD
device:
  type: cpu
epochs: 200
loss:
  params:
    epsilon: 1.0e-08
model:
  architecture: resnet18
  layers:
  - layer1
  - layer2
  - layer3
  - layer4
model_settings:
  use_amp_mixed_precision: false
  use_channels_last: true
optimizer:
  active: AdamW
  configs:
    AdamW:
      lr: 0.001
      weight_decay: 0.01
    SGD:
      lr: 0.4
      momentum: 0.9
      weight_decay: 0.0001
scheduler:
  params:
    epochs: 200
    max_lr: 0.01
  type: OneCycleLR
