dataloader:
  batch_size: 64
dataset:
  base_path: Images
  class: grid
  img_size: 256
  name: MVTecAD
device:
  type: cpu
epochs: 200
loss:
  params:
    epsilon: 1.0e-08
model:
  architecture: tf_efficientnet_lite1
  layers:
  - blocks.1
  - blocks.2
  - blocks.4
  - blocks.6
model_settings:
  use_amp_mixed_precision: false
  use_channels_last: true
optimizer:
  active: AdamW
  configs:
    AdamW:
      lr: 0.001
      weight_decay: 0.01
    SGD:
      lr: 0.4
      momentum: 0.9
      weight_decay: 0.0001
scheduler:
  params:
    epochs: 200
    max_lr: 0.01
    steps_per_epoch: 5
  type: OneCycleLR
